config/routes.rb
MysjAdmin::Application.routes.draw do
  resources :students
  resources :sessions, only: [:new, :create, :destroy]
  resources :payments, except: [:edit, :update]

  root to: 'students#show'

  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id           :integer          not null, primary key
#  student_id   :integer
#  amount_cents :integer
#  currency     :string(255)
#  method       :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  for          :string(255)
#  memo         :string(255)
#

class Payment < ActiveRecord::Base
  attr_accessible :amount_cents, :currency, :method, :for, :memo
  belongs_to :student

	before_save { |p| p.amount_cents *= 100 }

 	validates :amount_cents, presence: true
 	validates :currency, presence: true
 	validates :method, presence: true
 	validates :student_id, presence: true
 	validates :for, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	helper_method :sort_column, :sort_direction

	before_filter :signed_in_check
	before_filter :admin_check, only: [:new, :create, :destroy]


	def new
		@payment = Payment.new
		@students = Student.order("given_name ASC").find_all_by_enrolled_now(true)
	end

	def create
		@student = Student.find_by_id(params[:student_id])
		@payment = @student.payments.build(params[:payment])
		if @payment.save
			flash[:success] = "Payment record for #{@student.given_name} added!"
      redirect_to new_payment_url
    else
    	@students = Student.find_all_by_enrolled_now(true)
      render 'new'
    end
	end

	def index
		if current_student.admin?
			@payments = Payment.joins(:student).order(sort_column + " " + sort_direction)
		else
			@payments = current_student.payments.joins(:student).order(sort_column + " " + sort_direction)
		end
	end

	def destroy
		payment = Payment.find(params[:id])
		payment.destroy
		flash[:success] = "Record deleted."
		redirect_to payments_url
	end

	private
		def sort_column
			column_names = Payment.column_names + ["given_name", "surname"]
			column_names.include?(params[:sort]) ? params[:sort] : "created_at"
		end

		def sort_direction
			["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
		end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment.html.erb
<tbody>
	<tr>
		<th><%= payment.student.given_name %></th>
		<th><%= payment.student.surname %></th>
		<th><%= number_with_precision(payment.amount_cents.to_f / 100, precision: 2) %></th>
		<th><%= payment.currency %></th>
		<th><%= payment.method %></th>
		<th><%= payment.for %></th>
		<th><%= payment.memo %></th>
		<th><%= payment.created_at.to_date %></th>
		<th><% if current_student.admin? %>
		| <%= link_to "delete", payment, method: :delete, data: { confirm: "You sure? The record will be permanently deleted."} %>
		<% end %></th>
</tbody>

app/views/payments/index.html.erb
<% provide(:title, 'Payment history') %>

	<h1>Payment History</h1>
		<% if @payments.any? %>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th><%= sortable "given_name"%></th>
						<th><%= sortable "surname" %></th>
						<th><%= sortable "amount_cents", "Amount" %></th>
						<th><%= sortable "currency" %></th>
						<th><%= sortable "method" %></th>
						<th><%= sortable "purpose" %></th>
						<th><%= sortable "memo" %></th>
						<th><%= sortable "created_at", "Created" %></th>
					</tr>
				</thead>
				<%= render @payments %>
		<% else %>
			<p>Nothing here yet.</p>
		<% end %>

<% if current_student.admin? %>
	<%= link_to "Add payment", new_payment_path %>
<% end %>

app/views/payments/new.html.erb
<% provide(:title, 'Add payment') %>
<h1>Add a New Payment</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@payment) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= select_tag(:student_id,
					options_for_select(@students.map { |s| ["#{s.given_name} #{s.surname}", s.id] }))
			%>
			<%= f.label :currency %>
			<%= f.select(:currency, [['USD', 'USD'], ['RMB', 'RMB']]) %>

			<%= f.label :amount_cents, "Amount"%>
			<%= f.number_field :amount_cents %>

			<%= f.label :method %>
			<%= f.select(:method, [['Check', 'check'], ['Cash', 'cash'], ['Credit', 'credit']]) %>

			<%= f.label :for %>
			<%= f.select(:for, [['Tuition', 'tuition'], ['Disciple fee', 'disciple'], ['Form', 'form'],
													['Registration', 'registration'], ['Test', 'test'],
													['Other - specify in memo', 'other']])
			%>

			<%= f.label :memo, "Memo (optional)" %>
			<%= f.text_field :memo %>

			<%= f.submit "Create payment record" %>
		<% end %>
	</div>
</div>