config/routes.rb
MysjAdmin::Application.routes.draw do
  resources :students
  resources :sessions, only: [:new, :create, :destroy]
  resources :payments, except: [:edit, :update]

  root to: 'students#show'

  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "MYSJ Home", root_path, id: "logo" %>
			<nav>
				<ul class="nav nav-pills pull-right">
					<% if signed_in? %>
						<li><%= link_to "Hi, #{current_student.given_name}", current_student %></li>
						<li><%= link_to "Payments", payments_path %><li>
						<li><%= link_to "Settings", edit_student_path(current_student) %></li>
						<li><%= link_to "All students", students_path if current_student.admin? %></li>
						<li class="active"><%= link_to("Add a new student", new_student_path) if current_student.admin? %></li>
						<li><%= link_to "Sign out", signout_path, method: "delete"%></li>
					<% else %>
						<li> <%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MYSJ Students | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>